# -*- coding: utf-8 -*-
"""ToRUN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ClJ1ksv100-Jx54vF--k4sFQAs5LIlyZ
"""

!pip install pyngrok bokeh pathway

import subprocess

bokeh_proc = subprocess.Popen([
    "bokeh", "serve", "model1_app.py",
    "--port=5007",
    "--allow-websocket-origin=*"
])

#RUN model 1
from pyngrok import ngrok
ngrok.set_auth_token("2zXhrBe9HOfWxGwORleHm0ImbBL_2m2Aza42QULdN9mAcyEGQ")
public_url = ngrok.connect(5007)
print("🌍 Bokeh dashboard available at:", public_url)

bokeh_proc = subprocess.Popen([
    "bokeh", "serve", "model2_app.py",
    "--port=5009",
    "--allow-websocket-origin=*"
])

#run model 2
from pyngrok import ngrok
ngrok.set_auth_token("2zXhrBe9HOfWxGwORleHm0ImbBL_2m2Aza42QULdN9mAcyEGQ")
public_url = ngrok.connect(5009)
print("🌍 Bokeh dashboard available at:", public_url)

#to kill all bokeh servers
from pyngrok import ngrok
ngrok.kill()
!pkill -f bokeh